authentication/urls.py
from django.conf.urls import url
from .views import login, register, register_user, authenticate_user

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^login/authenticate/$', authenticate_user, name='authenticate-user'),
    url(r'^register/$', register, name='register'),
    url(r'^register/register-user/$', register_user, name='register-user'),
]

bmnc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from authentication import urls as authentication
from profil import urls as profil
from berita import urls as berita
from polling import urls as polling

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(berita, namespace='berita')),
    url(r'^akun/', include(authentication, namespace='authentication')),
    url(r'^profil/', include(profil, namespace='profil')),
    url(r'^polling/', include(polling, namespace='polling')),
]

authentication/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

authentication/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.db import connection
from datetime import datetime
from core.models import *

response = {}


def login(request):
    html = 'login.html'
    return render(request, html, response)


def register(request):
    html = 'register.html'
    return render(request, html, response)

def authenticate_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    response = {}
    try:
        userAuth = Narasumber.objects.raw("SELECT * FROM %s WHERE username='%s'" % (Narasumber._meta.db_table, username))[0]
        passAuth = Narasumber.objects.raw("SELECT * FROM %s WHERE password='%s'" % (Narasumber._meta.db_table, password))[0]
    except Exception:
        userAuth = None
        passAuth = None
    if userAuth is None and passAuth is None:
        return HttpResponseRedirect(reverse('authentication:login'))
        
    response['userAuth'] = userAuth
    response['passAuth'] = passAuth
    html = 'profil.html'
    return render(request, html, response)
    

def register_user(request):
    id = Narasumber.objects.last().id + 1
    role = request.POST.get('role')
    username = request.POST.get('username')
    password = request.POST.get('password')
    no_id = request.POST.get('no_id')
    nama = request.POST.get('nama')
    tempat_lahir  = request.POST.get('tempat_lahir')
    tanggal_lahir = request.POST.get('tanggal_lahir')
    email = request.POST.get('email')
    no_hp = request.POST.get('phone')
    status_kemahasiswaan = request.POST.get('student_status')
    id_univ = request.POST.get('id_univ')

    with connection.cursor() as cursor:
        sqlSelected = ""
        if role == "mahasiswa":
            sqlNarasumber = "INSERT INTO narasumber VALUES (%d, '%s', '%s', '%s', '%s', '%s', '%s', '%s');" % (id, username, password, nama, email, tempat_lahir, tanggal_lahir, no_hp, id_univ)
            sqlSelected = "INSERT INTO mahasiswa VALUES (%d, '%s', '%s');" % (id, no_id, status_kemahasiswaan)
        elif role == "staff":
            sqlNarasumber = "INSERT INTO narasumberr VALUES (%d, '%s', '%s', '%s', '%s', '%s', '%s', '%s');" % (id, username, password, nama, email, tempat_lahir, tanggal_lahir, no_hp, id_univ)
            sqlSelected = "INSERT INTO staf VALUES (%d, '%s', '%s');" % (id, no_id, id_univ)
        else:
            sqlNarasumber = "INSERT INTO narasumber VALUES (%d, '%s', '%s', '%s', '%s', '%s', '%s', '%s');" % (id, username, password, nama, email, tempat_lahir, tanggal_lahir, no_hp, id_univ)
            sqlSelected = "INSERT INTO dosen VALUES (%d, '%s', '%s');" % (id, no_id, id_univ)
        cursor.execute(sqlNarasumber)
        cursor.execute(sqlSelected)

    return HttpResponseRedirect(reverse('authentication:login'))

authentication/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="#">
  <title>BMNC : Login</title>
  <meta name="description" content="BMNC">
  <meta name="keywords" content="BMNC">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
  <!-- Script: Make my navbar transparent when the document is scrolled to top -->
  <script src="{% static 'js/navbar-ontop.js' %}"></script>
  <!-- Script: Animated entrance -->
  <script src="{% static 'js/animate-in.js' %}"></script>
</head>

<body>
  <!-- Navbar -->
  <!-- Cover -->
  <div class="align-items-center d-flex cover section-aquamarine py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center text-lg-left text-center">
          <h1 class="mb-0 mt-5 display-4">BMNC</h1>
          <p class="mb-5"></p>
        </div>
        <div class="col-lg-6 p-3">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a href="" class="active nav-link" data-toggle="pill" data-target="#tabone">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" data-toggle="pill" data-target="#tabtwo">Register</a>
            </li>
          </ul>
          <div class="tab-content mt-2">
            <div class="tab-pane fade show active" id="tabone" role="tabpanel">
              <form class="" method="GET" action="{% url 'authentication:authenticate-user' %}">
                <div class="form-group">
                  <label>Username</label>
                  <input type="email" class="form-control" placeholder="Enter username">
                </div>
                <div class="form-group">
                  <label>Password</label>
                  <input type="password" class="form-control" placeholder="Password"> </div>
                  <small class="form-text text-muted">Never share your password with anyone else.</small>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
            <div class="tab-pane fade" id="tabtwo" role="tabpanel">
              <p class="lead" contenteditable="true">Don't have an account yet?</p>
              <a class="btn btn-primary" href="/akun/register">Register!</a>
            </div>
            <div class="tab-pane fade" id="tabthree" role="tabpanel">
              <p class="">Tab pane three. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center bg-dark pt-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 p-3">
          <h2 class="mb-4">Contact</h2>
          <p class="m-0">
            <a href="tel:+246 - 542 550 5462" class="text-white">+62 123 456 789</a>
          </p>
          <p>
            <a href="mailto:cs@bmnc.com" class="text-white">cs@bmnc.com</a>
          </p>
        </div>
        <div class="col-md-6 p-3">
          <h2 class="mb-4">Location</h2>
          <p>
            <a href="https://www.google.it/maps" target="blank" class="text-white">Fasilkom UI, Kampus UI Depok</a>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 mt-3">
          <p class="text-center text-muted">© Copyright 2018 Adi, Raden, Norman. </p>
        </div>
      </div>
    </div>
  </div>
  <!-- JavaScript dependencies -->
  <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- Script: Smooth scrolling between anchors in the same page -->
  <script src="{% static 'js/smooth-scroll.js' %}"></script>
</body>

</html>

authentication/templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="#">
  <title>BMNC : Registration</title>
  <meta name="description" content="BMNC">
  <meta name="keywords" content="BMNC">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
  <!-- Script: Make my navbar transparent when the document is scrolled to top -->
  <script src="{% static 'js/navbar-ontop.js' %}"></script>
  <!-- Script: Animated entrance -->
  <script src="{% static 'js/animate-in.js' %}"></script>

  <script src="{% static 'js/form.js' %}"></script>
</head>

<body>
  <!-- Navbar -->
  <!-- Cover -->
  <div class="align-items-center d-flex cover section-aquamarine py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 p-3">
          <form class="p-4 bg-light" method="POST" action="{% url 'authentication:register-user' %}">
            <h4 class="mb-4 text-center">Register as a Narasumber</h4>
            <div class="form-group">
              <label>Role : </label>
              <select name="role">
                <option value="mahasiswa">Mahasiswa</option>
                <option value="staff">Staff</option>
                <option value="dosen">Dosen</option>
              </select> </div>
            <div class="form-group">
              <label>Username</label>
              <input class="form-control" placeholder="Your username" required="required" name="username"> </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" class="form-control" placeholder="Set your password" required="required" name="password"> </div>
            <div class="form-group">
              <label>Nomor Identitas</label>
              <input type="number" class="form-control" id="nomor-id" placeholder="Your identity number" required="required" name="no-id"> </div>
            <div class="form-group">
              <label>Nama</label>
              <input class="form-control" placeholder="Your name" required="required" name="nama"> </div>
            <div class="form-group">
              <label>Tempat lahir</label>
              <input class="form-control" placeholder="Your place of birth" required="required" name="tempat_lahir"> </div>
            <div class="form-group">
              <label>Tanggal lahir</label>
              <input type="date" class="form-control" placeholder="Your date of birth" required="required" name="tanggal_lahir"> </div>
            <div class="form-group">
              <label>Email</label>
              <input type="email" class="form-control" placeholder="Your email" required="required" name="email"> </div>
            <div class="form-group">
              <label>Nomor HP</label>
              <input type="number" class="form-control" placeholder="Your phone number" name="phone"> </div>
            <div class="form-group">
              <label>Status Kemahasiswaan</label>
              <input class="form-control" placeholder="Your student status" required="required" name="student_status"> </div>
            <div class="form-group">
              <label>ID Universitas : </label>
              <select required name="id_univ">
                <option value="ui">UI</option>
                <option value="itb">ITB</option>
                <option value="ugm">UGM</option>
                <option value="bsi">BSI</option>
              </select> </div>  
            <button type="submit" class="btn mt-4 btn-block p-2 btn-primary">
              <b>Register</b>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- Intro -->
  <!-- Gallery -->
  <!-- Menu -->
  <!-- Carousel reviews -->
  <!-- Carousel venue -->
  <!-- Events -->
  <!-- Parallax section -->
  <!-- Footer -->
  <!-- JavaScript dependencies -->
  <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- Script: Smooth scrolling between anchors in the same page -->
  <script src="{% static 'js/smooth-scroll.js' %"></script>
  </pingendo>
</body>

</html>