berita/urls.py
from django.conf.urls import url
from .views import buat_berita, daftar_berita, detail_berita, tambah_komentar, tambah_rating

urlpatterns = [
    url(r'^$', daftar_berita, name='daftar-berita'),
    url(r'^berita/$', buat_berita, name='buat-berita'),
    url(r'^berita/(?P<url_berita>[^\/]+)/$', detail_berita, name='detail-berita'),
    url(r'^berita/(?P<url_berita>[^\/]+)/tambah-rating/$', tambah_rating, name='tambah-rating'),
    url(r'^berita/(?P<url_berita>[^\/]+)/tambah-komentar/$', tambah_komentar, name='tambah-komentar'),
]

bmnc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from authentication import urls as authentication
from profil import urls as profil
from berita import urls as berita
from polling import urls as polling

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(berita, namespace='berita')),
    url(r'^akun/', include(authentication, namespace='authentication')),
    url(r'^profil/', include(profil, namespace='profil')),
    url(r'^polling/', include(polling, namespace='polling')),
]

berita/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

berita/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.db import connection
from datetime import datetime
from core.models import *


def buat_berita(request):
    response = {}
    html = 'buat_berita.html'
    return render(request, html, response)


def daftar_berita(request):
    response = {}
    response['daftar_berita'] = Berita.objects.raw("SELECT * FROM %s" % (Berita._meta.db_table))
    html = 'daftar_berita.html'
    return render(request, html, response)


def detail_berita(request, url_berita):
    response = {}
    berita = Berita.objects.raw("SELECT * FROM %s WHERE url='%s'" % (Berita._meta.db_table, url_berita))[0]
    try:
        riwayat = Riwayat.objects.raw("SELECT * FROM %s WHERE url_berita='%s'" % (Riwayat._meta.db_table, url_berita))[-1]
    except Exception:
        riwayat = None
    daftar_komentar = Komentar.objects.raw("SELECT * FROM %s WHERE url_berita='%s'" % (Komentar._meta.db_table, url_berita))
    rating = Rating.objects.raw("SELECT * FROM %s WHERE url_berita='%s' AND ip_address='%s'" % (Rating._meta.db_table, url_berita, get_client_ip(request)))
    if len(list(rating)) == 1:
        response['my_rating'] = rating[0].nilai
    else:
        response['my_rating'] = None
    response['berita'] = berita
    response['riwayat'] = riwayat
    response['daftar_komentar'] = daftar_komentar
    response['url_berita'] = url_berita

    html = 'detail_berita.html'
    return render(request, html, response)


def tambah_komentar(request, url_berita):
    id = Komentar.objects.last().id + 1
    tanggal = datetime.now()
    jam = datetime.time(datetime.now())
    konten = request.POST.get('konten')
    nama_user = request.POST.get('nama_user')
    email_user = request.POST.get('email_user')
    url_user = request.POST.get('url_user')

    with connection.cursor() as cursor:
        sql = "INSERT INTO komentar VALUES (%d, '%s', '%s', '%s', '%s', '%s', '%s', '%s');" % (id, tanggal, jam, konten, nama_user, email_user, url_user, url_berita)
        cursor.execute(sql)

    return HttpResponseRedirect(reverse('berita:detail-berita', kwargs={'url_berita': url_berita}))


def tambah_rating(request, url_berita):
    ip = get_client_ip(request)
    nilai = request.POST.get('nilai')

    with connection.cursor() as cursor:
        sql = "INSERT INTO rating VALUES ('%s', '%s', %s);" % (url_berita, ip, nilai)
        cursor.execute(sql)

    return HttpResponseRedirect(reverse('berita:detail-berita', kwargs={'url_berita': url_berita}))


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

berita/templates/buat_berita.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block content %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/buat_berita.css' %}"> </head>

<div class="py-5 bg-secondary">
<div class="align-items-center d-flex cover py-5" style="background-image: url(&quot;assets/restaurant/cover_light.jpg&quot;);">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 p-3">
          <h1>Buat berita</h1>
          <div class="tab-content mt-2">
            <div class="tab-pane fade show active" id="tabone" role="tabpanel">
              <form class="">
                <div class="form-group">
                  <label>Judul</label>
                  <input type="text" class="form-control" placeholder="Masukkan Judul">
                  <small class="form-text">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                  <label>URL</label>
                  <input type="text" class="form-control" placeholder="text">
                </div>
                <div class="form-group">
                  <label>Topik</label>
                  <input type="text" class="form-control" placeholder="text">
                </div>
                <div class="form-group">
                  <label>Jumlah Kata</label>
                  <input type="text" class="form-control" placeholder="text">
                </div>
                <div class="form-group">
                  <label>Tag</label>
                  <input type="text" class="form-control" placeholder="text">
                </div>
                <div class="form-group">
                  <label>Password</label>
                  <input type="password" class="form-control" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

berita/templates/daftar_berita.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">
  <h1>Daftar berita</h1>
  {% for berita in daftar_berita %}
    <div>
      <a href="/berita/{{ berita.url }}">{{ berita.judul }}</a>
    </div>
  {% endfor %}
  List url:
  <ul>
    <li><a href="/"> / : daftar berita</a></li>
    <li><a href="berita/"> berita/ : buat berita</a></li>
    <li><a href="berita/accept-sound/"> berita/url-berita/ : isi/detail dari berita</a></li>
    <li><a href="akun/login/"> akun/login/ : login</a></li>
    <li><a href="akun/register/"> akun/register/ : register</a></li>
    <li><a href="polling/"> polling/ : daftar polling</a></li>
    <li><a href="polling/berita/"> polling/berita/ : buat polling berita</a></li>
    <li><a href="polling/biasa/"> polling/biasa/ : buat polling biasa</a></li>
    <li><a href="profil/1/"> profil/username/ : profil</a></li>
  </ul>
</div>
{% endblock %}

berita/templates/detail_berita.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
<div class="align-items-center cover py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 p-3">
        <h1>{{ berita.judul }}</h1>
        <p> average rating: {{ berita.rerata_rating }} </p>
        <div class="tab-content mt-2">
          <p style="text-align: justify;">
            {{ riwayat.konten }}
          </p>
        </div>
      </div>
    </div>
    <h3>Komentar</h3>
    {% for komentar in daftar_komentar %}
      <div class="row">
        <div class="col-lg-2 p-3">
          <img class="img-circle"
            src="http://www.engr.uconn.edu/~gelyko/images/people_pic/anonymous.png"
            width="70" height="70">
        </div>
        <div class="col-lg-10 p-3">
          <div class="tab-content mt-2">
            <p><a href="{{ komentar.url_user }}"> {{ komentar.nama_user }}</a> | {{ komentar.email_user }} </p>
            <p style="text-align: justify;">
              {{ komentar.konten }}
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
    <div class="row">
        <div class="col-lg-10">
            <form class="" method="POST" action="{% url 'berita:tambah-komentar' url_berita=url_berita %}">
                {% csrf_token %}
                <div class="form-group">
                  <label>Nama</label>
                  <input type="text" class="form-control" placeholder="Nama" name="nama_user">
                </div>
                <div class="form-group">
                  <label>Email</label>
                  <input type="email" class="form-control" placeholder="Email" name="email_user">
                </div>
                <div class="form-group">
                  <label>URL</label>
                  <input type="text" class="form-control" placeholder="URL" name="url_user">
                </div>
                <div class="form-group">
                  <label>Komentar</label>
                  <textarea class="form-control" placeholder="Komentar" name="konten">
                  </textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-lg-2">
            {% if my_rating %}
              <div>
                Rating Saya: {{ my_rating }}
              </div>
            {% else %}
              <form class="" method="POST" action="{% url 'berita:tambah-rating' url_berita=url_berita %}">
                  {% csrf_token %}
                  <div class="form-group">
                    <label>Rating</label>
                    <select class="form-control" name="nilai" id="register_tipe">
                      <option value="5">5</option>
                      <option value="4">4</option>
                      <option value="3">3</option>
                      <option value="2">2</option>
                      <option value="1">1</option>
                    </select>
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            {% endif %}
        </div>
    </div>
  </div>
</div>
{% endblock %}